[language-server.docker-language-server]
command = "docker-language-server"
args = ["start", "--stdio"]

[[language]]
name = "dockerfile"
language-servers = ["docker-language-server"]

[[language]]
name = "toml"
auto-format = true
