[language-server.kdl-lsp]
command = "kdl-lsp"

[[language]]
name = "bash"
file-types = [{ glob = "dot_{bashrc,profile,zprofile,zshrc}" }]

[[language]]
name = "kdl"
language-servers = ["kdl-lsp"]

[[language]]
name = "toml"
file-types = ["toml", { glob = "*.toml.tmpl" }]
