#:schema https://mise.jdx.dev/schema/mise.json

[tools]
aube = "latest"
bat = "latest"
cargo-binstall = "latest"
delta = "latest"
fd = "latest"
"forgejo:mergiraf/mergiraf" = "latest"
gitui = "latest"
helix = "latest"
jq = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
zellij = "latest"

[settings]
locked_scopes = ["project"]
auto_update = true
auto_update_check_duration = "1d"

[settings.github]
oauth_client_id = "Iv23liYiP3f4sWC5csxy"
