#:schema https://mise.jdx.dev/schema/mise.json

[tools]
aube = "latest"
bat = "latest"
delta = "latest"
fd = "latest"
gitui = "latest"
helix = "latest"
jq = "latest"
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
zellij = "latest"

[settings]
experimental = true
minimum_release_age = "7d"

[settings.github]
oauth_client_id = "Iv23liYiP3f4sWC5csxy"
