#:schema https://mise.jdx.dev/schema/mise.json

[tools]
starship = "latest"
usage = "latest"
uv = "latest"
bat = "latest"
delta = "latest"
fd = "latest"
ripgrep = "latest"
helix = "latest"
jq = "latest"
